version: "3.3"
services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - "8080:8080"
    restart: on-failure
    image: johnazedo/bff
    env_file:
      - .env
